## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: restart todos-app
  run: 'docker compose restart todos-app'
  change: 'services/one/**/*'

# - name: restart todos-app
#   run: 'docker compose restart todos-app'
#   change: 'services/two/**/*'
