## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: restart main app
  run: 'docker compose restart web'
  change: [
    'app/**/*',
    'nginx/default.conf',
    'docker-compose.yml'
  ]
  ignore: ['services/**/*']

- name: restart todos-app
  run: 'docker compose restart todos-app'
  change: 'services/todos/**/*'
  ignore: ['**/*.db', '**/*.db-journal']

- name: restart chat-app
  run: 'docker-compose restart chat-app'
  change: 'services/chat/**/*'
  ignore: [ 'services/chat/target/**/*' ]

- name: restart news-app
  run: 'docker-compose restart news-app'
  change: 'services/news/**/*'
  ignore: ['**/*.db', '**/*.db-journal']
