services:
  web:
    build: .
    ports:
      - "4040:80"

    volumes:
      - ./app:/usr/share/nginx/html

  todos-app:
    build: services/todos
    ports:
      - "4001:4001" # Web Server
    volumes:
      - ./services/todos:/app

  chat-app:
    build: services/chat
    ports:
      - "4002:4002" # Web Server
    volumes:
      - ./services/chat/src:/app/src
